### ISSUE TITLE
Browser running multiple browsers in Selenium Grid dockerized

### ISSUE THREAD

**Issue by mpluta-airhelp** [galenframework/galen#546]
Hello,

Problem I have is to make my test run to use specific browser available inn grid.  Even better it should use all browsers that I set in parametrised test. But for now I am running test with command:

```
docker-compose run --rm -u $(id -u)  galenframework galen test tests/suites/NewHomePage.test --groups STAG -Dbase_url=some_base_url   --htmlreport report -Dbrowser=chrome
```

and my test looks like this:
```
@@ table devices
    | deviceName | tags      | size     |
    | Mobile     | mobile    | 360x700  |
    | Tablet     | tablet    | 780x800  |
    | Desktop    | desktop   | 1024x768 |

@@ parameterized using devices
@@ groups EPP, STAG
New homepage on ${deviceName} device ${browser}
    Website Homepage v2017 | ${base_url}test-front-page-2017/ ${size} ${browser}
        wait 3s
        check specs/homepage.gspec --include "${tags}"

```
Problem is that this command does not override galen.browserFactory.selenium.grid.browser config param:

galen.config:

```
galen.range.approximation=2
galen.default.browser=chrome
$.webdriver.chrome.driver=/usr/local/bin/chromedriver
spec.colorscheme.precision = 256
galen.browser.screenshots.fullPage.scrollTimeout = 50
galen.browser.screenshots.fullPage.scrollWait = 20
spec.colorscheme.testrange = 6
galen.browserFactory.selenium.runInGrid = true
galen.browserFactory.selenium.grid.url = http://hub:4444/wd/hub
galen.browserFactory.selenium.grid.browser = firefox
galen.test.suffix=.test
galen.test.js.file.suffix=.test.js
galen.browser.pageElement.areaFinder = native

```

Here is my docker setup:

docker-compose.yml
```
version: '2'
services:
  galenframework:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/galen
    links:
      - seleniumhub:hub
  seleniumhub:
    image: selenium/hub:3.8.1-aluminum
    ports:
      - "4444"
    environment:
      GRID_TIMEOUT: 0
  chrome_node:
    image: selenium/node-chrome:3.8.1-aluminum
    links:
      - seleniumhub:hub
    ports:
      - "5900"
    environment:
      HUB_PORT_4444_TCP_ADDR: seleniumhub
      HUB_PORT_4444_TCP_PORT: 4444
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      SCREEN_DEPTH: 24
    shm_size: 1536m
  firefox_node:
    image: selenium/node-firefox:3.8.1-aluminum
    links:
      - seleniumhub:hub
    ports:
      - "5900"
    environment:
      HUB_PORT_4444_TCP_ADDR: seleniumhub
      HUB_PORT_4444_TCP_PORT: 4444
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
      SCREEN_DEPTH: 24
    shm_size: 1536m

```

and Dockerfile
```
FROM java:8

ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 6.11.4
ENV GALEN_VERSION 2.3.6


# Install nvm with node and npm
RUN curl https://raw.githubusercontent.com/creationix/nvm/v0.31.0/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default \
    && npm install -g galenframework-cli@$GALEN_VERSION


ENV NODE_PATH      $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH           $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

RUN mkdir -p /usr/src/galen
WORKDIR /usr/src/galen

```

Am I missing sth? 

Regards!
Mateusz
